version: '3'

services:
  cicd:
    build: .
    container_name: build_env
    volumes:
      - cicd-volume:/usr/local/boxfuse/boxfuse-sample-java-war-hello/target

  prod:
    image: tomcat:8.5-jre8-alpine
    container_name: prod_env
    ports:
      - "80:8080"
    volumes:
      - cicd-volume:/usr/local/tomcat/webapps/

volumes:
  cicd-volume: