---
# tasks file for webserver
- name: Make sure that nginx installed
  apt:
    name: nginx
    state: present

- name: Check index.html
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0777
  notify:
    - restart nginx
